### ISSUE TITLE
Formato Preço (Plano e assinatura)

### ISSUE THREAD

**Issue by cartafelipe** [rodrigodmpa/pagarme-api#3]
Na listagem de Planos e assinaturas favor:
-converter o preço para decimal;
-exibir o R$.

**Comment by rodrigodmpa** [comment]
Feito

**Comment by cartafelipe** [comment]
Rodrigo. O preço no pagar.me é cadastrado em centavos, como cada 1 real tem 100 centavos. Temos que dividir o valor do preço do plano por 100.
Ex.: (Plano vereador) Preço 10.000/100 = R$100,00
Favor conferir.
